### ISSUE TITLE
Extra files restores everything

### ISSUE THREAD

**Issue by jerone** [atom-community/sync-settings#107]
The default behavior of the "Extra Files" setting is that when restore is executed, it will create a file for every file from the gist. It does not check the extra-files setting at all on restore. 

I'm wondering if that is the best solution... If the gist includes files that you don't want on your machine you can't exclude them. For example a readme file explaining what the gist does. This could also be an security issue, as it will download every file without the user validating it.

On the other side, doing a restore for the first time on a new machine, you probably don't know all extra files.

I'm not sure if this a bug, or a feature. I'm leaning to a bug, but then we need to change something to make the first-time-on-new-machine logic work.

**Comment by almostearthling** [comment]
I wouldn't be so strict, IMO since there are both an auth token and a gist ID the user restoring settings probably knows what he's doing. However this is a good point, since one might have different machines (with different capabilities and different OSes), and I actually found the recent possibility to discard some items from sync quite precious, when I gained access to a small machine with Windows. So, possibly giving the user the possibility to at least classify *extra files* in order to be able to discard some of them on some instances of Atom could actually be a plus.

F.

**Comment by groupsky** [comment]
I assume the code in question is [this](https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L111). From the look of it smells like a security breach :wink: 

The only person who is supposed to change the gits is the user itself, and IMO this means the breach is possibly small. I would say to plan a better handling of these files, like checking with the custom files config and only restoring them, others should be ignored probably silently or with some unobtrusive indication.

On the topic of selecting which files to restore, I would argue that this is against the mission of this plugin - keeping multiple atom instances in sync. If the need is really there, I would suggest to just have multiple gists for each configuration. Then probably another product can provide a partial sync between them.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
