### ISSUE TITLE
Multiple 'workspaces'/setting configurations

### ISSUE THREAD

**Issue by janbaykara** [atom-community/sync-settings#125]
Much like Adobe Photoshop/Illustrator, it'd be cool to have defined 'workspaces' that encapsulate multiple Atom configurations.
- A workspace would house all settings, plugins, themes, custom styles etc.
- Workspaces would be enabled via a dropdown, a command palette option, but perhaps also assigned to specific filetypes. You might have a JS 'workspace' configuration, and a separate HTML one, with the plugin making the switch automatically.

Thoughts? ~~I may have a crack at a prototype PR for this in the next few weeks.~~

**Comment by victornpb** [comment]
I really wish I could do this, because I can't have all of my plugins enabled all the time, because it slows down so much, so it is a pain having to constantly switch back and fourth.

Would be really useful to have a workspace for working with html and css with plugins like emmet and pigments, another for refactoring code with things like ternjs and refactor lint enabled, the list goes on...

**Comment by dirk-thomas** [comment]
I am not sure if the described feature is in the scope of this package. In the case where different workspaces have the same settings and only enable / disable specific packages (for performance) this could be implemented in a separate package since it is orthogonal to what this package provides.

**Comment by victornpb** [comment]
I just switched to VSCode, I suits all my needs atm

**Comment by UziTech** [comment]
PRs are welcome

**Comment by UziTech** [comment]
This is out of scope for this package.

[Project Manager](https://github.com/danielbrodin/atom-project-manager#project-settings) lets you define different settings for each project
