### ISSUE TITLE
How to use wildcard or regex in Extra files definition

### ISSUE THREAD

**Issue by letientai299** [atom-community/sync-settings#258]
It's would be nice if sync-setting could take input at `*.coffee` and then sync all custom coffe scripts under `~/.atom`.

**Comment by kurtinlane** [comment]
+1
Not exactly the same but similar. It'd would awesome to be able to add folders and not just files under `~/.atom`.

For example I use this `textual-velocity` plugin that keeps notes under in a folder `~/.atom/notes/` It would be so cool if sync-settings allowed for unique folders to be sync as well as all the other awesome stuff it syncs. 

In order to do this it probably has to be repo and not just a gist. Unless you find every file under `notes` folder and put it at top level so gist can store it and then when you sync you store it back under a notes folder. Sounds like a real pain

Anyways love what the plugin does, just thought this might be useful for anyone who uses a plugin that adds plugin specific folders to `~/.atom/`. Then full functionality of all plugins could be synced across computers effortlessly. 

**Atom Version:**  1.9.9
**OS and Version:** OSX 10.11.6
