### ISSUE TITLE
Utilise GITHUB_TOKEN environment variable

### ISSUE THREAD

**Issue by danielbayley** [atom-community/sync-settings#343]
Why doesn't this package take any notice of `GITHUB_TOKEN`? It mentions something about using it during testing, but I already have it set (`GITHUB_TOKEN=$(security find-generic-password … **NOT** hard coded…)` in my shell startup file.

The [gist](https://atom.io/packages/gist) package for example, allows you to publish gists straight from Atom (so the same as this package effectively…) and it reads the token from `GITHUB_TOKEN`, whereas this package throws an error.

**Comment by dirk-thomas** [comment]
While the specs check this environment variable as well as the package settings (https://github.com/atom-community/sync-settings/blob/9098c5a4aa65365b90c5b4d4f98930df6519b199/spec/sync-settings-spec.coffee#L45) the "normal" (non-spec) code doesn't consider the environment variable. I assume nobody has implemented this since nobody had a use case for it yet.

It should be straight forward to extend the existing [getPersonalAccessToken](https://github.com/atom-community/sync-settings/blob/a8fe7a74af343d7e58ff459c9b2e981eeb6f9369/lib/sync-settings.coffee#L52-L56) function to also consider the environment variable. It would be great if you could provide a pull request for this enhancement.

**Comment by dirk-thomas** [comment]
Addressed by #357.
