### ISSUE TITLE
use a folder/file instead of a Gist

### ISSUE THREAD

**Issue by coreybrett** [atom-community/sync-settings#351]
Would be nice if a folder or file could be used for syncing instead of a Gist. Would work for SMB, NFS, Dropbox, Google Drive, etc.

**Comment by dirk-thomas** [comment]
Similar to #267.

**Comment by pksunkara** [comment]
Are there any blockers for this? If not, I would love to fix this.

**Comment by Zireael** [comment]
I support this request because it would allow us to share our setups with other people.
Let's say you set a perfect Atom environment and recommend to a friend (or your readers) to try Atom to code in Lua/JS/Python/whatever. Then people could install Atom, import sync-settings package and be geared up within minutes with help from someone who has already done hours of combing through plugins/syntax highlighters.
VS Code has a very nice feature where you can not only create plugins, but also packages of plugins (let's say: [all you need to do productive C# coding]). sync-settings could provide access to similar feature.

**Comment by UziTech** [comment]
PRs are welcome

**Comment by UziTech** [comment]
Sync-Settings now allows other packages to provide a location for the backup. You can install [sync-settings-folder-location](https://atom.io/packages/sync-settings-folder-location) and follow the install instructions to use a folder for the backup location.
