### ISSUE TITLE
Problem with self signed certificate

### ISSUE THREAD

**Issue by janstieler** [atom-community/sync-settings#371]
Hi,
After I updated to the Atom version 1.18 and tried to backup my sync-settings I got the error
`sync-settings: Error backing up your settings. (self signed certificate in certificate chain)`.
Bevor it worked perfectly.
Could someone help me to get it work again?

Cheers

**Comment by dirk-thomas** [comment]
In `sync-settings` itself nothing has changed in this area. I guess it is more likely that something in Atom / Electron has changed between the version you were using before (?) and Atom version 1.18. Maybe going through the changelog of those will reveal anything.

**Comment by janstieler** [comment]
Hi,
Thanks for the fast reply. The version I used bevor was 1.17.x.
Than I have to do a research for that problem in combination to Atom.
I will repot if I found a solution.

**Comment by dirk-thomas** [comment]
I will close this issue for now due to no response. Please feel free to comment and the ticket can be reopened.

**Comment by github-sjacobs** [comment]
I have been having this problem for several months. Since I already had my Mac configured as desired I never took the time to try to figure this out. Now I have just set up a new Windows 10 PC and can't restore my settings to the new laptop. I have been searching for a solution and not found anything that will work.

In the past this has worked great to keep configurations between Mac, Linux Mint, and Windows 10 synced up but I haven't been able to have success in a while. Note that when I select "view backup" it does show my gist with the appropriate contents.
Atom 1.39.1 x64
sync-settings 0.8.6

**Comment by hoodie63** [comment]
I'm having this problem too. Have tried setting ssl-strict false, same issue.

**Comment by mcandre** [comment]
Same issue in my environment. sync-settings does not have an obvious way to disable strict certificate validation, nor does it properly integrate with host CA stores.
