### ISSUE TITLE
The latest version no longer sync additional files

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom-community/sync-settings#408]
Just update to the latest version with latest atom 1.25-beta1. Noticed that the additional file like (project.cson) is no longer synced. If I update my settings to my gist. These previous backed up files are also removed.

**Comment by dirk-thomas** [comment]
I think this should be fixed by https://github.com/atom-community/sync-settings/pull/403/files#diff-cf50db55215de01a1c9b0703083818caR165. If you could try the latest code from the master branch and confirm that it works for you that would be great. Otherwise I will go ahead soon and release a new patch release.

**Comment by dirk-thomas** [comment]
Version 0.8.4 is out. I will close this assuming that it addresses your problem. Please feel free to comment if that is not the case and the ticket can be reopened.
