### ISSUE TITLE
Can't set proxy settings

### ISSUE THREAD

**Issue by baatochan** [atom-community/sync-settings#619]
I have a problem with using this package when behind a proxy. I looked for all already created issues in this repo and couldn't find a way to set it up properly.

I'm using Manjaro Linux and have proxy env var (http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY, etc.) set up. Atom gets its proxy settings from the env var. Sync settings does not even tho all issues here say it should be.

I found [this comment in #273](https://github.com/atom-community/sync-settings/issues/273#issuecomment-233842283) that shows the solution with sync-settings.coffee but I have no idea how to use that. I'd be very grateful if someone could help me.

**Comment by UziTech** [comment]
It seems like we would need to pass a `request` option to octokit [here](https://github.com/atom-community/sync-settings/blob/bb9118dfbae32ea213d8ff81a8e53bbe6c8ac428/lib/location/gist.js#L11) in order to get this to work. I don't have a proxy that I can test but if you are willing to create a PR I would be happy to merge it.

Alternatively you could use [`sync-settings-git-location`](https://github.com/UziTech/sync-settings-git-location) to sync to a git repo. I'm pretty sure that would work with git proxy settings.

**Comment by UziTech** [comment]
I created PR #620 that should work. Can you test it to see if it works for you?
